import { format } from 'date-fns'
import { Sparkles } from 'lucide-react'
import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'

import { MessageItem } from '@/components/chat/message-item'
import { Button } from '@/components/ui/button'
import { ROUTES } from '@/lib/constants'
import { getSharedChat } from '@/server/services/chat-service'

export const dynamic = 'force-dynamic'

interface PageProps {
  params: Promise<{ shareId: string }>
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { shareId } = await params
  const chat = await getSharedChat(shareId)

  return {
    title: chat ? `${chat.title} (shared)` : 'Shared chat',
    // Shared links are unlisted, not public — keep them out of search results.
    robots: { index: false, follow: false },
  }
}

export default async function SharedChatPage({ params }: PageProps) {
  const { shareId } = await params
  const chat = await getSharedChat(shareId)

  // A revoked link and a link that never existed are indistinguishable here,
  // by design: neither should confirm that a chat exists.
  if (!chat) notFound()

  return (
    <div className="flex min-h-dvh flex-col bg-background">
      <header className="sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur">
        <div className="mx-auto flex w-full max-w-3xl items-center gap-3 px-4 py-3 sm:px-6">
          <div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
            <Sparkles className="size-4" />
          </div>

          <div className="min-w-0 flex-1">
            <h1 className="truncate text-sm font-semibold">{chat.title}</h1>
            <p className="truncate text-xs text-muted-foreground">
              Shared conversation
              {chat.sharedAt &&
                ` · ${format(new Date(chat.sharedAt), 'd MMM yyyy')}`}
              {' · '}
              <span className="font-mono">{chat.model}</span>
            </p>
          </div>

          <Button size="sm" variant="outline" asChild className="shrink-0">
            <Link href={ROUTES.home}>Open LLM Dev Kit</Link>
          </Button>
        </div>
      </header>

      <main className="flex-1">
        <div className="mx-auto w-full max-w-3xl divide-y divide-border/60">
          {chat.messages.map((message) => (
            // readOnly hides edit, regenerate and delete — a visitor has no
            // account and no write access to this conversation.
            <MessageItem key={message.id} message={message} readOnly />
          ))}
        </div>
      </main>

      <footer className="border-t border-border py-6 text-center text-xs text-muted-foreground">
        <p>
          This is a read-only snapshot. Responses were generated by an AI model
          and may contain mistakes.
        </p>
      </footer>
    </div>
  )
}
